# Contribution by Cloud Native Guatemala folks :)
# This workflow will check if a localized content is outdated or not
# by comparing English content in the old branch and the latest branch.
---
name: Reusable step

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language with changes to create issue'
        required: true

jobs:
  language:
    runs-on: ubuntu-latest
    steps:
       - name: Test of creating Issue
         run: |
           echo "Var: ${{ inputs.language }}"
    #  - uses: JasonEtco/create-an-issue@v2
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      ASSIGNEES: sergioarmgpl, Dianmz
    #      LABELS: help wanted,translations,good first issue,issue/tracking
    #    with:
    #      update_existing: true
    #      filename: website/content/${{ github.event.inputs.language }}_files.md